export enum ConfigValuesType {
  NODE_ENV = 'NODE_ENV',

  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASS = 'DATABASE_PASS',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_PORT = 'DATABASE_PORT',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  CACHE_REDIS_DATABASE = 'CACHE_REDIS_DATABASE',
  CACHE_REDIS_NAMESPACE = 'CACHE_REDIS_NAMESPACE',
  CACHE_REDIS_TTL = 'CACHE_REDIS_TTL',
  CACHE_MEMORY_TTL = 'CACHE_MEMORY_TTL',
  CACHE_MEMORY_LRU = 'CACHE_MEMORY_LRU',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
}
